### ISSUE TITLE
Model not working on long audios

### ISSUE THREAD

**Issue by HotzingTone** [biboamy/TVSM-dataset#4]
Hello! Thanks for this great work!
I am trying out the model to get speech/music segmentations, it works fine (using predictor.py) on short audios but aborts when working on long ones.
Would you have any suggestions?
Thank you again!

**Comment by biboamy** [comment]
Hello, thanks for reporting this issue! I have tried audio around 1 hour and it seems fine on my computer. Can you share a little bit more information so that I can trouble-shoot the issue? For example, when you encountered this issue, what is the error message and how long is your input audio?

**Comment by HotzingTone** [comment]
Thanks for getting back! The audio I tried is around 2 hours. After `python predictor.py`, it run in silence for about 1 or 2 minutes, during which I monitored that it consumed about 20Gb storage, until the terminal threw `killed` and quit.
For what's worth, here I uploaded the audio file if it helps: https://drive.google.com/file/d/1cGpz_wFgOULnlsJnJa4JTrIb8Dpwb1wa
Thank you very much!!!

**Comment by HotzingTone** [comment]
Thank you so much Amy! It works perfectly on my side! Great one!
