### ISSUE TITLE
Can not pull checkpoints (This repository is over its LFS data quota.)

### ISSUE THREAD

**Issue by owlwang** [biboamy/TVSM-dataset#6]
```bash

# git-lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/biboamy/TVSM-dataset.git/info/lfs'

```

It appears that due to GitHub's restrictions on downloading large files, the checkpoint could not be downloaded. Would it be possible to host the checkpoint somewhere else?

**Comment by biboamy** [comment]
Hello, thanks for raising this issue. You can download the checkpoint from [this path](https://drive.google.com/drive/folders/1THtEHYUh1lueUFH37n2VAhVy8n2QfNpp?usp=sharing) and manually put them into the repository. Let me know if this works. Thanks!

**Comment by owlwang** [comment]
Thanks!
